meuapp/urls.py
from django.urls import path
from django.contrib.auth import views as auth_view


from meuapp.views import CreateAccount, UsuarioPList

app_name ='meuapp'

urlpatterns = [
    path('', UsuarioPList.as_view(), name='list_usuariolist'),
    path('login/', auth_view.LoginView.as_view(template_name='login.html'), name='login'),
    path('createaccount/', CreateAccount.as_view(), name='createaccount'),
]

tributodevidoteste/urls.py
from django.contrib import admin
from django.urls import path, include
from .api import api

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('meuapp.urls', namespace='meuapp')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('api/v2/', api.urls),

]

meuapp/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):
    endereco = models.CharField(max_length=20, null=True, blank=True)

meuapp/forms.py
from meuapp.models import Usuario
from django.contrib.auth.forms import UserCreationForm
from django import forms

class FormMainPage(forms.Form):
    email = forms.EmailField(label=False)


class CreateAccountForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = Usuario
        fields = ('username', 'endereco')

meuapp/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import FormView
from django.views.generic import ListView, CreateView
from meuapp.forms import CreateAccountForm
from meuapp.models import Usuario
from django.shortcuts import reverse


class CreateAccount(FormView):
    template_name = "createaccount.html"
    form_class = CreateAccountForm

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)
    def get_success_url(self):
        return reverse('meuapp:list_usuariolist')

class HomehospedagemNovo(LoginRequiredMixin, CreateView):
    model = Usuario
    form_class = CreateAccountForm


class UsuarioPList(LoginRequiredMixin, ListView):
    paginate_by = 10
    model = Usuario
    template_name = 'usuariolist_list.html'

    def get_queryset(self):
        return Usuario.objects.all().order_by('id')

meuapp/templates/createaccount.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sua Página</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
    <link href="{% static 'css/tiny-slider.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>
<body>

<header>
    <div class="container mt-4">
        <div class="row justify-content-center">
            <div class="col-lg-6">
                <form method="post">
                    {% csrf_token %}
                    <fieldset class="form-group">
                        <legend class="text-left">Crie uma conta para continuar</legend>
                        <div class="mb-3">
                            <label for="id_username" class="form-label">Nome do Usuario:</label>
                            <input type="text" class="form-control" id="id_username" name="username">
                            {% for error in form.username.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <label for="id_email" class="form-label">Email:</label>
                            <input type="email" class="form-control" id="id_email" name="email">
                            {% for error in form.email.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <label for="id_password1" class="form-label">Senha:</label>
                            <input type="password" class="form-control" id="id_password1" name="password1">
                            {% for error in form.password1.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ error }}
                                </div>
                            {% endfor %}
                            {% if form.password1.help_text %}
                                <small class="text-muted">{{ form.password1.help_text }}</small>
                            {% endif %}
                        </div>
                        <div class="mb-3">
                            <label for="id_password2" class="form-label">Confirmar Senha:</label>
                            <input type="password" class="form-control" id="id_password2" name="password2">
                            {% for error in form.password2.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>
                        <div class="mb-3">
                            <label for="id_endereco" class="form-label">Endereço:</label>
                            <input type="text" class="form-control" id="id_endereco" name="endereco">
                            {% for error in form.endereco.errors %}
                                <div class="invalid-feedback d-block">
                                    {{ error }}
                                </div>
                            {% endfor %}
                        </div>

                        </div>
                    </fieldset>
                    <button type="submit" class="btn btn-primary">Criar Conta</button>
                </form>
            </div>
        </div>
    </div>
</header>

</body>
</html>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

meuapp/templates/login.html
{% load static %}
<form method="post" class="mt-4 mx-auto text-center" style="max-width: 400px;">
  {% csrf_token %}
  <div class="form-group">
    <label for="id_username" class="text-left">Username:</label>
    <input type="text" class="form-control" id="id_username" name="username">
    {% for error in form.username.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
  </div>
  <div class="form-group">
    <label for="id_password" class="text-left">Password:</label>
    <input type="password" class="form-control" id="id_password" name="password">
    {% for error in form.password.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    <br>
  </div>
  <div class="form-group">
    <button type="submit" class="btn btn-primary">Login</button>
  </div>
  <br>
          <div class="d-flex justify-content-center mt-4">
            <a href="{% url 'meuapp:createaccount' %}" class="btn btn-primary">Criar uma nova conta</a>
        </div>

</form>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

meuapp/templates/usuariolist_list.html
{% block main %}

    <div class="container text-center">
        <h2 class="mt-4 mb-4 border-bottom pb-2">Lista de Usuários</h2>

        <table class="table table-striped table-bordered mx-auto" style="max-width: 600px;">
            <thead>
                <tr>
                    <th scope="col">Usuário</th>
                </tr>
            </thead>
            <tbody>
                {% for usuario in page_obj.object_list %}
                <tr>
                    <td>
                        <span>{{ usuario }}</span>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="1" class="text-center">Nenhum usuário encontrado</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <div class="d-flex justify-content-center mt-4">
            <a href="{% url 'meuapp:createaccount' %}" class="btn btn-primary">Criar uma nova conta</a>
        </div>
    </div>
{% endblock %}

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>